/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package microcontrollergui;

import java.awt.Color;
import java.awt.event.KeyEvent;

/**
 *
 * @author Hp
 */
public class MicroGUI extends javax.swing.JFrame {

    /**
     * Creates new form MicroGUI
     */
    public MicroGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        left_btn = new javax.swing.JButton();
        forward_btn = new javax.swing.JButton();
        right_btn = new javax.swing.JButton();
        back_btn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Observer_table = new javax.swing.JTable();
        stop_btn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        up_signal = new javax.swing.JButton();
        down_signal = new javax.swing.JButton();
        right_signal = new javax.swing.JButton();
        left_signal = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(0, 0, 800, 800));
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        left_btn.setBackground(new java.awt.Color(255, 255, 153));
        left_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/microcontrollergui/arrows  left.jpg"))); // NOI18N
        left_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                left_btnActionPerformed(evt);
            }
        });
        getContentPane().add(left_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 390, 85, 85));

        forward_btn.setBackground(new java.awt.Color(0, 0, 0));
        forward_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/microcontrollergui/arrows.jpg"))); // NOI18N
        forward_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                forward_btnActionPerformed(evt);
            }
        });
        getContentPane().add(forward_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 300, 87, 85));

        right_btn.setBackground(new java.awt.Color(255, 255, 153));
        right_btn.setForeground(new java.awt.Color(51, 0, 51));
        right_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/microcontrollergui/arrows_right.jpg"))); // NOI18N
        right_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                right_btnActionPerformed(evt);
            }
        });
        getContentPane().add(right_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 390, 85, 85));

        back_btn.setBackground(new java.awt.Color(255, 255, 153));
        back_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/microcontrollergui/arrows - down.jpg"))); // NOI18N
        back_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back_btnActionPerformed(evt);
            }
        });
        getContentPane().add(back_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 480, 85, 85));

        Observer_table.setFont(new java.awt.Font("Maiandra GD", 0, 14)); // NOI18N
        Observer_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null}
            },
            new String [] {
                "LEFT", "RIGHT", "STRAIGHT", "BACK"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        Observer_table.setRowHeight(28);
        jScrollPane1.setViewportView(Observer_table);
        if (Observer_table.getColumnModel().getColumnCount() > 0) {
            Observer_table.getColumnModel().getColumn(0).setResizable(false);
            Observer_table.getColumnModel().getColumn(3).setResizable(false);
        }

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 130, 359, 50));

        stop_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/microcontrollergui/stop-button-red-clip-art.png"))); // NOI18N
        stop_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                stop_btnMouseClicked(evt);
            }
        });
        getContentPane().add(stop_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(487, 433, 102, 100));
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 658, 26));

        jLabel2.setBackground(new java.awt.Color(255, 51, 51));
        jLabel2.setFont(new java.awt.Font("Maiandra GD", 1, 24)); // NOI18N
        jLabel2.setText("Observer Table");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 100, 200, 30));

        up_signal.setBackground(new java.awt.Color(0, 153, 0));
        getContentPane().add(up_signal, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 200, 70, 70));

        down_signal.setBackground(new java.awt.Color(0, 153, 0));
        getContentPane().add(down_signal, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 340, 70, 70));

        right_signal.setBackground(new java.awt.Color(0, 153, 0));
        getContentPane().add(right_signal, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 270, 70, 70));

        left_signal.setBackground(new java.awt.Color(0, 153, 0));
        getContentPane().add(left_signal, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 270, 70, 70));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/microcontrollergui/background1.jpg"))); // NOI18N
        jLabel1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jLabel1KeyPressed(evt);
            }
        });
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 630));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void right_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_right_btnActionPerformed
        rightClick();
        
    }//GEN-LAST:event_right_btnActionPerformed

    private void back_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back_btnActionPerformed
        backClick();
       
    }//GEN-LAST:event_back_btnActionPerformed

    private void forward_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_forward_btnActionPerformed
        forwardClick();
        
    }//GEN-LAST:event_forward_btnActionPerformed

    private void left_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_left_btnActionPerformed
        leftClick();
        
    }//GEN-LAST:event_left_btnActionPerformed

    private void stop_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_stop_btnMouseClicked
        System.out.println("Method to stop the motion");
        update_Table(100, 120, 55, 12);
        
    }//GEN-LAST:event_stop_btnMouseClicked

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        System.out.println("I am pressed");
        if (evt.getKeyCode() == KeyEvent.VK_UP){
            System.out.println("I am pressed");
           forwardClick();
        }
        if (evt.getKeyCode() == KeyEvent.VK_DOWN){
            backClick();
        }
        if (evt.getKeyCode() == KeyEvent.VK_RIGHT){
            rightClick();
        }
        if (evt.getKeyCode() == KeyEvent.VK_LEFT){
            leftClick();
        }
    }//GEN-LAST:event_formKeyPressed

    private void jLabel1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jLabel1KeyPressed
    
    }//GEN-LAST:event_jLabel1KeyPressed

    public void leftClick(){
        System.out.println("Moves left");
    }
    public void rightClick(){
        System.out.println("Moves right");
    }
    public void forwardClick(){
        System.out.println("Moves forward");
    }
    public void backClick(){
        System.out.println("Moves backward");
    }
    /**
     * @param args the command line arguments
     */
    
    public void update_Table(int left,int right,int straight,int back){
        Observer_table.setValueAt(left, 0, 0);
        Observer_table.setValueAt(right, 0, 1);
        Observer_table.setValueAt(straight, 0, 2);
        Observer_table.setValueAt(back, 0, 3);
        
        if(left>100){
            left_signal.setBackground(new java.awt.Color(0, 153, 0));
        }
        else if(left>50){
            left_signal.setBackground(Color.YELLOW);
        }
        else{
            left_signal.setBackground(Color.RED);
        }
        
        
        if(right>100){
            right_signal.setBackground(new java.awt.Color(0, 153, 0));
        }
        else if(right>50){
            right_signal.setBackground(Color.YELLOW);
        }
        else{
            right_signal.setBackground(Color.RED);
        }
        if(straight>100){
            up_signal.setBackground(new java.awt.Color(0, 153, 0));
        }
        else if(straight>50){
            up_signal.setBackground(Color.YELLOW);
        }
        else{
            up_signal.setBackground(Color.RED);
        }
        if(back>100){
            down_signal.setBackground(new java.awt.Color(0, 153, 0));
        }
        else if(back>50){
            down_signal.setBackground(Color.YELLOW);
        }
        else{
            down_signal.setBackground(Color.RED);
        }
        
        
        
    }
            
            
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MicroGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MicroGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MicroGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MicroGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MicroGUI().setVisible(true);
            
            
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Observer_table;
    private javax.swing.JButton back_btn;
    private javax.swing.JButton down_signal;
    private javax.swing.JButton forward_btn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton left_btn;
    private javax.swing.JButton left_signal;
    private javax.swing.JButton right_btn;
    private javax.swing.JButton right_signal;
    private javax.swing.JButton stop_btn;
    private javax.swing.JButton up_signal;
    // End of variables declaration//GEN-END:variables
}
